name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          rsync -av --exclude .git ./ /root/ros2_ws/src/ros2_stdio_bridge/
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --packages-select ros2_stdio_bridge

      - name: test
        run: |
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          colcon test --packages-select ros2_stdio_bridge
          colcon test-result --verbose

